# Use an existing Docker image as the base image
FROM my-ubuntu:latest

# Set the working directory inside the container
WORKDIR /

# Run the following command to install dependencies
RUN apt-get update && apt-get install -y make build-essential libstdc++6